apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingchallenge-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lighttpd
  template:
    metadata:
      labels:
        app: lighttpd
    spec:
      containers:
        - name: lighttpd
          image: robindeclerck/shippingchallenge
          env:
            - name: DATABASE_HOST
              value: mysql-service
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_DB
              value: shippingChallenge
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: shippingchallenge-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: lighttpd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shippingchallenge-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: shippingchallenge.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shippingchallenge-service
                port:
                  number: 80