version: "3.4"
services:
  lighttpd:
    build:
      context: .
    container_name: "Lighttpd"
    links:
      - database
    ports:
      - "81:80"
    tty: true

  database:
    image: mysql:8.0
    container_name: "MySQL_Database"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro