version: "3.4"
services:
  app:
    build:
      context: .
    container_name: "Flask-App"
    links:
      - database
    ports:
      - 5000:5000

  database:
    image: mysql:8.0
    container_name: "MySQL_Database"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro